#!/usr/bin/env python3
from __future__ import annotations

import json
import math
from pathlib import Path

CONFIG_FILE = "config.json"


def fmt3(v):
    return f"{v[0]} {v[1]} {v[2]}"


def wavelength_to_rgb(wavelength_nm):
    w = float(wavelength_nm)

    if 380 <= w < 440:
        r, g, b = -(w - 440) / (440 - 380), 0.0, 1.0
    elif 440 <= w < 490:
        r, g, b = 0.0, (w - 440) / (490 - 440), 1.0
    elif 490 <= w < 510:
        r, g, b = 0.0, 1.0, -(w - 510) / (510 - 490)
    elif 510 <= w < 580:
        r, g, b = (w - 510) / (580 - 510), 1.0, 0.0
    elif 580 <= w < 645:
        r, g, b = 1.0, -(w - 645) / (645 - 580), 0.0
    elif 645 <= w <= 700:
        r, g, b = 1.0, 0.0, 0.0
    else:
        r = g = b = 0.0

    if 380 <= w < 420:
        factor = 0.3 + 0.7 * (w - 380) / (420 - 380)
    elif 420 <= w < 645:
        factor = 1.0
    elif 645 <= w <= 700:
        factor = 0.3 + 0.7 * (700 - w) / (700 - 645)
    else:
        factor = 0.0

    gamma = 0.8

    def correct(c):
        return 0.0 if c <= 0.0 else (c * factor) ** gamma

    return correct(r), correct(g), correct(b)


def axis_t(axis, i, j, k, nx, ny, nz):
    axis = axis.upper()

    if axis == "X":
        return i / max(nx - 1, 1)
    if axis == "Y":
        return j / max(ny - 1, 1)
    if axis == "Z":
        return k / max(nz - 1, 1)

    raise ValueError(f"Invalid axis {axis!r}. Use X, Y, or Z.")


def zone_falloff(t, zone):
    width = max(float(zone["width"]), 1e-6)
    position = float(zone["position"])
    return math.exp(-((t - position) / width) ** 2)


def sigma_s(volume, i, j, k, nx, ny, nz):
    t = axis_t(volume["axis"], i, j, k, nx, ny, nz)
    sr = sg = sb = 0.0

    for zone in volume["zones"]:
        r, g, b = wavelength_to_rgb(zone["wavelength"])
        falloff = zone_falloff(t, zone)
        peak = float(zone.get("sigma_s_peak", 0.0))

        sr += peak * falloff * r
        sg += peak * falloff * g
        sb += peak * falloff * b

    return sr, sg, sb


def sigma_a(volume, i, j, k, nx, ny, nz, fallback):
    t = axis_t(volume["axis"], i, j, k, nx, ny, nz)
    ar = ag = ab = 0.0
    used_zone_absorption = False

    for zone in volume["zones"]:
        if "sigma_a_peak" not in zone:
            continue

        r, g, b = wavelength_to_rgb(zone["wavelength"])
        falloff = zone_falloff(t, zone)
        peak = float(zone["sigma_a_peak"])

        ar += peak * falloff * r
        ag += peak * falloff * g
        ab += peak * falloff * b
        used_zone_absorption = True

    if not used_zone_absorption:
        return fallback[0], fallback[1], fallback[2]

    return ar, ag, ab


def write_medium(volume, grid, out_dir):
    nx, ny, nz = grid["resolution"]
    mn, mx = grid["world_min"], grid["world_max"]
    fallback_sigma_a = grid.get("sigma_a", [0.0, 0.0, 0.0])
    out = out_dir / volume["file"]

    with out.open("w", encoding="utf-8") as f:
        f.write(f'MakeNamedMedium "{volume["name"]}"\n')
        f.write('    "string type"   [ "rgbgrid" ]\n')
        f.write(f'    "integer nx"    [ {nx} ]\n')
        f.write(f'    "integer ny"    [ {ny} ]\n')
        f.write(f'    "integer nz"    [ {nz} ]\n')
        f.write(f'    "point3 p0"     [ {mn} {mn} {mn} ]\n')
        f.write(f'    "point3 p1"     [ {mx} {mx} {mx} ]\n')
        f.write(f'    "float g"       [ {grid.get("g", 0.0)} ]\n')

        f.write('    "rgb sigma_a"   [\n')
        for k in range(nz):
            for j in range(ny):
                for i in range(nx):
                    ar, ag, ab = sigma_a(volume, i, j, k, nx, ny, nz, fallback_sigma_a)
                    f.write(f"        {ar:.8f} {ag:.8f} {ab:.8f}\n")
        f.write("    ]\n")

        f.write('    "rgb sigma_s"   [\n')
        for k in range(nz):
            for j in range(ny):
                for i in range(nx):
                    sr, sg, sb = sigma_s(volume, i, j, k, nx, ny, nz)
                    f.write(f"        {sr:.8f} {sg:.8f} {sb:.8f}\n")
        f.write("    ]\n")

    return out


def write_scene(cfg, out_dir):
    scene = out_dir / "master_scene.pbrt"

    film = cfg["film"]
    camera = cfg["camera"]
    integrator = cfg["integrator"]
    sampler = cfg["sampler"]
    lights = cfg["lights"]

    with scene.open("w", encoding="utf-8") as f:
        f.write("############################################################\n")
        f.write(f'# PROJECT: {cfg["project"]["name"]}\n')
        f.write("# FILE: generated/master_scene.pbrt\n")
        f.write("# GENERATED BY: build_scene.py\n")
        f.write("############################################################\n\n")

        f.write(f'Integrator "{integrator["type"]}" "integer maxdepth" [{integrator["maxdepth"]}]\n')
        f.write(f'Sampler "{sampler["type"]}" "integer pixelsamples" [{sampler["pixelsamples"]}]\n\n')

        f.write('Film "rgb"\n')
        f.write(f'    "integer xresolution" [{film["xresolution"]}]\n')
        f.write(f'    "integer yresolution" [{film["yresolution"]}]\n')
        f.write(f'    "string filename" ["{film["filename"]}"]\n\n')

        f.write(f'LookAt {fmt3(camera["eye"])}  {fmt3(camera["target"])}  {fmt3(camera["up"])}\n')
        f.write(f'Camera "perspective" "float fov" [{camera["fov"]}]\n\n')
        f.write("WorldBegin\n\n")

        f.write("    # --- MEDIA ---\n")
        for v in cfg["volumes"]:
            f.write(f'    Include "{v["file"]}"\n')
        f.write("\n")

        f.write("    # --- VOLUME CONTAINERS ---\n")
        for v in cfg["volumes"]:
            reverse_orientation = bool(v.get("reverse_orientation", False))

            f.write("    AttributeBegin\n")
            f.write(f"        Translate {fmt3(v['translate'])}\n")
            f.write(f"        Scale {fmt3(v.get('scale', [1, 1, 1]))}\n")

            if reverse_orientation:
                f.write("        ReverseOrientation\n")

            f.write(f'        MediumInterface "{v["name"]}" ""\n')
            f.write('        Material "interface"\n')
            f.write(f'        Shape "plymesh" "string filename" ["../{v["container_mesh"]}"]\n')
            f.write("    AttributeEnd\n\n")

        bowl = cfg.get("bowl")
        if bowl and bowl.get("enabled", False):
            f.write("    # --- BOWL ---\n")
            f.write("    AttributeBegin\n")
            
            f.write(f"        Translate {fmt3(bowl.get('translate', [0, 0, 0]))}\n")

            rot = bowl.get("rotate", [0, 0, 0])

            if rot[0] != 0:
                f.write(f"        Rotate {rot[0]} 1 0 0\n")
            if rot[1] != 0:
                f.write(f"        Rotate {rot[1]} 0 1 0\n")
            if rot[2] != 0:
                f.write(f"        Rotate {rot[2]} 0 0 1\n")

            f.write(f"        Scale {fmt3(bowl.get('scale', [1, 1, 1]))}\n")
            
            
            mat = bowl.get(
                "material",
                {
                    "type": "diffuse",
                    "reflectance": bowl.get("reflectance", [0.75, 0.68, 0.55])
                },
            )

            if mat.get("type") == "dielectric":
                eta = mat.get("eta", 1.52)
                f.write(f'        Material "dielectric" "float eta" [{eta}]\n')
            else:
                refl = mat.get("reflectance", bowl.get("reflectance", [0.75, 0.68, 0.55]))
                f.write(f'        Material "diffuse" "rgb reflectance" [{fmt3(refl)}]\n')

            f.write(f'        Shape "plymesh" "string filename" ["../{bowl["file"]}"]\n')
            f.write("    AttributeEnd\n\n")

        ground = cfg.get("ground")
        if ground and ground.get("enabled", False):
            y = ground.get("y", -1.5)
            size = ground.get("size", 5.0)
            refl = ground.get("reflectance", [0.35, 0.35, 0.35])

            f.write("    # --- GROUND PLANE ---\n")
            f.write("    AttributeBegin\n")
            f.write(f'        Material "diffuse" "rgb reflectance" [{fmt3(refl)}]\n')
            f.write('        Shape "bilinearmesh"\n')
            f.write(f'            "point3 P" [ {-size} {y} {-size}\n')
            f.write(f'                         {-size} {y} { size}\n')
            f.write(f'                          { size} {y} {-size}\n')
            f.write(f'                          { size} {y} { size} ]\n')
            f.write('            "point2 uv" [ 0 0  0 1  1 0  1 1 ]\n')
            f.write("    AttributeEnd\n\n")

        p = lights["point"]
        f.write('    LightSource "point"\n')
        f.write(f'        "blackbody I" [{p["temperature"]}]\n')
        f.write(f'        "float scale" [{p["scale"]}]\n')
        f.write(f'        "point3 from" [{fmt3(p["from"])}]\n\n')

        inf = lights["infinite"]
        f.write('    LightSource "infinite"\n')
        f.write(f'        "blackbody L" [{inf["temperature"]}]\n')
        f.write(f'        "float scale" [{inf["scale"]}]\n')

    return scene


def main():
    with open(CONFIG_FILE, "r", encoding="utf-8") as f:
        cfg = json.load(f)

    out_dir = Path(cfg["project"]["output_dir"])
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"Project: {cfg['project']['name']}")
    print(f"Output directory: {out_dir}")

    for volume in cfg["volumes"]:
        print(f"Wrote medium: {write_medium(volume, cfg['volume_grid'], out_dir)}")

    print(f"Wrote scene:  {write_scene(cfg, out_dir)}")
    print("\nNext:")
    print("    bash bash_automation/run_05_rgb_grid.sh")


if __name__ == "__main__":
    main()
